name: Build app

on:
  push:
    branches:
      - main
      - ci-woes
  pull_request:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      include:
        - platform: "switch"
          ext: "nro"
        - platform: "pc"
          ext: "bin"
  container:
    image: ghcr.io/fortheusers/sealeo:latest
  steps:
  - uses: actions/checkout@main
  - name: Build ${{ matrix.platform }} binary
    run: make ${{ matrix.platform }}
  - uses: actions/upload-artifact@v3
    with:
      name: ${{ matrix.platform }}.${{ matrix.ext }}
      path: /code/${{ matrix.platform }}.${{ matrix.ext }}