name: Build app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: pc
            ext: bin
          - platform: wii
            ext: dol
          - platform: wiiu
            ext: wuhb
          - platform: 3ds
            ext: 3dsx
          - platform: switch
            ext: nro
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.platform }} binary
      run: make ${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
        name: WiiFiUShowMii.${{ matrix.ext }}
        path: /__w/WiiFiUShowMii/WiiFiUShowMii/WiiFiUShowMii.${{ matrix.ext }}
